// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMd4nR0aTp9VSpoHpTuMuF_UzDa4f5K30',
    appId: '1:762833992202:web:b17d55043fbb550f783df3',
    messagingSenderId: '762833992202',
    projectId: 'rehan-traders-edb1d',
    authDomain: 'rehan-traders-edb1d.firebaseapp.com',
    storageBucket: 'rehan-traders-edb1d.firebasestorage.app',
    measurementId: 'G-DEZBRDCDGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAYadUkbc16UkOsXFQkQVUDJtuJuaqY0c',
    appId: '1:762833992202:android:2c477a10ec15c112783df3',
    messagingSenderId: '762833992202',
    projectId: 'rehan-traders-edb1d',
    storageBucket: 'rehan-traders-edb1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhzaO7SZxgwA3r1e3l7S8YQJPYnI0ca5M',
    appId: '1:762833992202:ios:1ee59b24595ebb81783df3',
    messagingSenderId: '762833992202',
    projectId: 'rehan-traders-edb1d',
    storageBucket: 'rehan-traders-edb1d.firebasestorage.app',
    iosBundleId: 'com.example.rehanTraderWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhzaO7SZxgwA3r1e3l7S8YQJPYnI0ca5M',
    appId: '1:762833992202:ios:1ee59b24595ebb81783df3',
    messagingSenderId: '762833992202',
    projectId: 'rehan-traders-edb1d',
    storageBucket: 'rehan-traders-edb1d.firebasestorage.app',
    iosBundleId: 'com.example.rehanTraderWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMd4nR0aTp9VSpoHpTuMuF_UzDa4f5K30',
    appId: '1:762833992202:web:2b4ccd0d64c70a16783df3',
    messagingSenderId: '762833992202',
    projectId: 'rehan-traders-edb1d',
    authDomain: 'rehan-traders-edb1d.firebaseapp.com',
    storageBucket: 'rehan-traders-edb1d.firebasestorage.app',
    measurementId: 'G-MP0EWL6D24',
  );

}